server:
  port: 9527
spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      routes: #路由可以有多个
        - id: payment_route   #路由id 没有固定规则，但要求唯一，建议配合服务名
          uri: http://localhost:8001
          predicates:
            - Path=/payment/get/**  #断言，路径相匹配的进行路由
#       - id: payment_route2   #路由id 没有固定规则，但要求唯一，建议配合服务名
#           uri: http://localhost:8001
#           predicates:
#             - Path=/discovery/**  #断言，路径相匹配的进行路由
eureka:
  client:
    register-with-eureka: true
    fetchRegistry: true
    serviceUrl:
      #集群版
      #defaultZone: http://localhost:7001/eureka/,http://localhost1:7002/eureka/
      #单机版
      defaultZone: http://localhost1:7001/eureka/


