server:
  port: 80
spring:
  application:
    name: cloud-counsumer-hystrix-order
#服务客户端
eureka:
  client:
    register-with-eureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:7001/eureka/
  instance:
    instance-id: order80
    prefer-ip-address: true #访问路径显示ip
feign:
  hystrix:
    enabled: true