server:
  port: 8401
spring:
  application:
    name: cloudalibaba-sentinel-service
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.100.180:1111
    sentinel:
      transport:
        dashboard: 192.168.100.180:8080
        port: 8719
        clientIp: 192.168.100.180
          # nacos配置持久化
      datasource:
        ds1:
          nacos:
            server-addr: 192.168.100.180:1111
            dataId: sentinel-ruoyi-gateway
            groupId: DEFAULT_GROUP
            data-type: json
            rule-type: flow
management:
  endpoints:
    web:
      exposure:
        include: '*'