server:
  port: 8002
spring:
  application:
    name: cloud-provider-service

#服务客户端
eureka:
  client:
    register-with-eureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:7001/eureka/,http://localhost:7002/eureka/
  instance:
    instance-id: provider8002
    prefer-ip-address: true #访问路径显示ip

---